# Source Path
source ~/.path

# Local config
[[ -f ~/.dotfiles/local/zshrc ]] && source ~/.dotfiles/local/zshrc

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/vendor/zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.dotfiles/vendor/zprezto/init.zsh"
fi

# Load direnv
eval "$(direnv hook zsh)"

